apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: jxu
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
    
        image: registry.dev.afsmtddso.com/jxu-harbor-project/app:7786cd9-a0f05e9
        ports:
        - containerPort: 5000
